server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  # mustache
  mustache:
    servlet:
      expose-session-attributes: true
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/security?serverTimezone=Asia/Seoul
    username: sysim
    password: sysim
  # jpa
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  # security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 500656441244-d1bvp8gg8k583jh9v4emseblgnj859ft.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://127.0.0.1:8082/login/oauth2/code/google
            scope:
              - email
              - profile
