server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/security?serverTimezone=Asia/Seoul
    username: sysim
    password: sysim
  # jpa
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 500656441244-u3paa07v9397ihb5u16cqp9imbmjtati.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://127.0.0.1:8082/login/oauth/code/google
            scope:
              - email
              - profile
